### ISSUE TITLE
Help pls!

### ISSUE THREAD

**Issue by Neepy73** [DexxKnight1/Jurassic-World-Reborn-II#4]
Hi, new to this mod on CurseForge, fresh install and I go to play it and it just gets stuck on the screen linked below. Any suggestions or answers would be terrific. Cheers 

![Screenshot 2023-05-09 221126](https://github.com/DexxKnight1/Jurassic-World-Reborn-II/assets/133022448/c95573d3-47f5-483d-823a-1f4b822e6030)

**Comment by DexxKnight1** [comment]
This mod is called ModDirector and hes use to install OptiFine on first start for you automatically. As I see you have some issues with this mod, so the solution (FIX) for you is to install OptiFine manually or, if you don't want to play with OptiFine, to disable the ModDirector mod in the mod folder.
