### ISSUE TITLE
[Bug]: Crafting station bug

### ISSUE THREAD

**Issue by Megarock-msn** [DexxKnight1/Jurassic-World-Reborn-II#5]
### General Info

- [X] I didn't added any mods
- [X] I get this issue consistently in single-player
- [X] I get this issue consistently in multi-player
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

CurseForge

### Modpack version

v5.0.3

### Describe your issue

i have just downloaded the modpack through CurseForge.
when i open the tinkers construct crafting station i can put on armor i craft but the ui for putting it on is placed in the middle of the crafting area making it difficult to craft any item but the problem doesn't appear when i use a normal crafting table and the problem is consistent in all worlds i have created

### Steps to reproduce the issue

1. i downloaded the pack fresh
2. i opened up a world
3. made af crafting station
4. tried to open it to craft with
5. the armor ui was in the way

### Additional Information

there is no crashes in the modpack

**Comment by Megarock-msn** [comment]
if there is a way for me to fix it myself so i dont waste anyone's time to much i will gladly try. also i forgot to add a picture of the problem so here it is if you can open it that is
![Bug image crafting station](https://github.com/DexxKnight1/Jurassic-World-Reborn-II/assets/150623769/f2762420-f89b-4b06-bd3e-e75750f96b28)

**Comment by DexxKnight1** [comment]
Is comes from the **Visible Armor Slots unofficial** mod. To fix it, just disable/delete/remove that mod. I'll try to fix in the next update or remove it as well.

**Comment by Megarock-msn** [comment]
thank you for helping
